# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('leaders', models.ManyToManyField(blank=True, related_name='leader_in', to='people.Person')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.UnitType'),
        ),
        migrations.AddField(
            model_name='person',
            name='membership',
            field=models.ManyToManyField(related_name='members', to='people.Unit'),
        ),
    ]
